Repository goftp/server, pull requests merged in 2018-04, with the labels that each got.

#39 Refactor parse list param
  cmd.go
  cmd_test.go
Labels: bug

#40 Add conn test
  conn.go
  conn_test.go
Labels: testing

#41 Implement Serve function to allow custom listeners
  server.go
  server_test.go
Labels: enhancement

#42 Improve shutdown behaviour
  logger.go
  server.go
  server_test.go
Labels: enhancement
